spring:
  config:
    import: 'optional:configserver:'

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL:localhost:5432/order_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: ""
    ssl:
      trust-store-location: classpath:ssl/kafka.server.truststore.jks
      trust-store-password: ${TRUST_STORE_PASSWORD}
      trust-store-type: PKCS12
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        max.block.ms: 10000
        max.in.flight.requests.per.connection: 5
        retries: 3
        delivery.timeout.ms: 120000
    consumer:
      group-id: hub-group
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 300000
    listener:
      ack-mode: manual
      concurrency: 3

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:18761/eureka}

topics:
  order:
    pending: ${TOPICS_ORDER_PENDING:prod-order-pending} # 주문 생성 및 대기(주문 -> 허브 방향으로 1차 이벤트 발송, 공급업체 재고 차감용)
    accepted: ${TOPICS_ORDER_ACCEPTED:prod-order-accepted} # 주문 승인(주문 -> 배송 방향으로 이벤트 발송)

  hub:
    stock-updated: ${TOPICS_HUB_STOCK_UPDATED:prod-hub-stock-updated} # 허브 재고 변경

  delivery:
    created: ${TOPICS_DELIVERY_CREATED:prod-delivery-created} # 배송 생성(배송 -> 주문 방향 이벤트 발송)
    status-updated: ${TOPICS_DELIVERY_STATUS_UPDATED:prod-delivery-status-updated} # 배송 상태 변경(배송완료/배송취소 시 배송->주문 방향 이벤트 발송)

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
