# src/main/resources/application-test.yml

spring:
  config:
    activate:
      on-profile: test

  cloud:
    config:
      discovery:
        enabled: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    # H2 인메모리 모드 설정
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    # H2 전용 SQL 방언 설정
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # 테스트 시마다 테이블을 새로 생성하고 종료 시 삭제
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# 토픽 설정
topics:
  order:
    pending: order-pending-topic
    accepted: order-accepted-topic
  hub:
    stock-updated: hub-update-topic

# 테스트 로그 상세 확인용
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.loopang.orderservice: DEBUG
    com.loopang.common: DEBUG
